---
# role: firewalld
# file: molecule/default/molecule.yml

dependency:
  name: "galaxy"
  options:
    requirements-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
    role-file: "${MOLECULE_PROJECT_DIRECTORY}/collections.yml"
driver:
  name: "podman"
provisioner:
  name: "ansible"
  config_options:
    defaults:
      forks: 8
      interpreter_python: "auto_silent"
      allow_world_readable_tmpfiles: true
      callbacks_enabled: "ansible.builtin.default"
      callback_result_format: "yaml"
      remote_tmp: "/tmp/.ansible/tmp"
      inject_facts_as_vars: false
    ssh_connection:
      pipelining: true
  log: true
  playbooks:
    converge: "../resources/playbooks/converge.yml"
    verify: "../resources/playbooks/verify.yml"
    prepare: "../resources/playbooks/prepare.yml"
    side_effect: "../resources/playbooks/side_effect.yml"
  inventory:
    group_vars:
      all:
        firewalld_services:
          - name: "molecule-web"
            description: "HTTP & HTTPS \"test\""
            ports:
              - port: "18080"
                protocol: "tcp"
        firewalld_ipsets:
          - name: "molecule-clients"
            type: "hash:ip"
            entries:
              - "192.0.2.10"
        firewalld_policies:
          - name: "molecule-egress"
            ingress_zone: "public"
            egress_zone: "ANY"
            ports:
              - port: "18443"
                protocol: "tcp"
            rules:
              - family: "ipv4"
                destination:
                  address: "198.51.100.10"
                action:
                  type: "reject"
                  reject_type: "icmp-host-prohibited"
        firewalld_zones:
          - name: "public"
            services:
              - "ssh"
              - "molecule-web"
            interfaces:
              - "{{ ansible_facts.default_ipv4.interface }}"
            tcp_mss_clamp: 1400
            rules:
              - family: "ipv4"
                source:
                  ipset: "molecule-clients"
                action:
                  type: "reject"
verifier:
  name: "ansible"
scenario:
  test_sequence:
    - "dependency"
    - "destroy"
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "check"
    - "verify"
    - "side_effect"
    - "converge"
    - "idempotence"
    - "verify"
    - "destroy"
  name: "default"
platforms:
  - name: "firewalld"
    image: "docker.io/${uns:-jomrr}/molecule-${img:-fedora}:${tag:-latest}"
    pre_build_image: true
    override_command: false
    systemd: "true"
    security_opts:
      - "label=disable"
    capabilities:
      - "NET_ADMIN"
      - "SYS_ADMIN"
