---
# role: firewalld
# file: molecule/resources/playbooks/prepare.yml

- name: "FIREWALLD | Prepare test containers"
  hosts: all
  gather_facts: true
  tasks:
    - name: "FIREWALLD | Allow package service actions"
      ansible.builtin.file:
        path: /usr/sbin/policy-rc.d
        state: absent

    - name: "FIREWALLD | Install process utilities in Debian containers"
      ansible.builtin.apt:
        name: procps
        state: present
        update_cache: true
      when: ansible_facts.os_family == 'Debian'
